name: validarPrBranch

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
            fetch-depth: 0 # needed to checkout all branches for this Action to work

      - name: Run script
        run: ./.github/scripts/validadorBranchPS.sh
        env:
            DIFF_PATHS: "*"
            BASE_SHA: ${{ github.event.pull_request.base.sha }}